# Generated by Django 4.2.6 on 2023-10-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
