# Generated by Django 4.2.6 on 2023-10-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preset', '0002_presetmodel_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='presetModel',
            new_name='post',
        ),
    ]
