# Generated by Django 4.2.6 on 2023-10-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preset', '0003_rename_presetmodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fileupload',
            field=models.FileField(blank=True, null=True, upload_to='file_uploads/'),
        ),
    ]
